### ISSUE TITLE
Feature request: Backup user keybinds

### ISSUE THREAD

**Issue by iNgeon** [ch3mz-za/SCUtil#10]
Can you please add the ability to backup the mappings in \Roberts Space Industries\StarCitizen\PTU\USER\Client\0\Controls\Mappings
Perhaps backup say to the Roberts Space Industries\StarCitizen\backups or alternatively a user select-able folder or perhaps even inside a SCUtil\backups\Mappings aka keybinds folder (perhjaps for both PTU and LIVE based on if they exist
Amend the xml binding file with .bckx extension where x represents a numerical increment or perhaps YYYY\MM\DD HH:mm:ss
Example layout_my_joystick_pu3.17.1_01-ingeon01g.xml.bck1 or 2023-02-17_19:09:05_layout_my_joystick.xml etc.

Perhaps in the screen mention that the user has to first manually export their custom bindings in Star Citizen game by going to 
Options >  Keybindings > Advanced Controls Customization > Control Profiles > Save Control Settings > "Custom user name"

**Comment by ch3mz-za** [comment]
Done

**Comment by iNgeon** [comment]
Great stuff. Thank you.
Please also add an an option for restore keybindings for Live and PTU as per the above.
