### ISSUE TITLE
Window Size

### ISSUE THREAD

**Issue by Donati5142** [ch3mz-za/SCUtil#21]
May I suggest increasing the application window size by default. It seems a little small, especially when you start to navigate through directories.

If you do click the button to increase the app to full screen size (Windows) or by dragging the corners, it changes back to default size as soon as some action was taken in the app by clicking on directory folders. (Using Win11 in my case)

Thank you for the latest changes, the flow of the app is much better.

**Comment by ch3mz-za** [comment]
Done

**Comment by iNgeon** [comment]
Some feedback, in V2.3.1 it does not persist
